apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-argo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sangkips/todo-example.git
    targetRevision: main
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: python-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
