name: Release flow

on:
    push:
        branches:
            - main
        paths-ignore:
        - package.json
        - CHANGELOG.md
env:
  DIST_PATH: dist
  RELEASE_PATH: output.zip

jobs:
    setup:
        name: Checkout & generate changelog
        runs-on: ubuntu-latest
    
        outputs:
          clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
          tag: ${{ steps.changelog.outputs.tag }}
          skipped: ${{ steps.changelog.outputs.skipped }}
    
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              ref: release
          - name: Generate Changelog
            id: changelog
            uses: TriPSs/conventional-changelog-action@v3
            with:
                git-message: 'chore(release): {version}'
                release-count: 0

          - name: create release
            uses: actions/create-release@v1
            if: ${{ steps.changelog.outputs.skipped == 'false'}}
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                tag_name: ${{ steps.changelog.outputs.tag }}
                release_name: ${{ steps.changelog.outputs.tag }}
                body: ${{ steps.changelog.outputs.clean_changelog }}